[package]
name = "loco-protobuf"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "examples/real-app"
]
resolver = "2"

[dependencies]
axum = { workspace = true }
bytes = "1"
prost = "0.13"
mime = "0.3"



[dev-dependencies]
tokio = { version = "1", features = ["full"] }
axum-test = "14"
tempfile = "3"
prost = { version = "0.13", features = ["derive"] }

[workspace.dependencies]
loco-rs = "0.16"
axum = "0.8"
tokio = { version = "1.45", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
prost = "0.13"
loco-protobuf = { path = "." }
