//! # Loco ProtoBuf
//!
//! A helper crate to easily integrate Protocol Buffers with [Loco.rs](https://loco.rs),
//! offering Axum-compatible extractors and responses.
//!
//! ## Features
//!
//! - **`Protobuf<T>` Extractor**: Automatically decodes `application/protobuf` request bodies into your Prost-generated structs.
//! - **`Protobuf<T>` Response**: Automatically encodes your structs into Protobuf format and sets the `Content-Type: application/protobuf` header.
//!
//! ## Usage
//!
//! ```rust,no_run
//! use axum::response::Result;
//! use loco_protobuf::Protobuf;
//! // use crate::proto::user::{UserRequest, UserResponse};
//!
//! // Define your Proto structs (usually generated by prost-build)
//! #[derive(prost::Message, Clone)]
//! pub struct UserRequest {
//!     #[prost(string, tag = "1")]
//!     pub id: String,
//! }
//!
//! #[derive(prost::Message, Clone)]
//! pub struct UserResponse {
//!     #[prost(string, tag = "1")]
//!     pub id: String,
//! }
//!
//! async fn create_user(
//!     Protobuf(req): Protobuf<UserRequest>,
//! ) -> Result<Protobuf<UserResponse>> {
//!     Ok(Protobuf(UserResponse {
//!         id: req.id,
//!     }))
//! }
//! ```

// pub mod gen;
use async_trait::async_trait;
use axum::{
    body::Bytes,
    extract::{FromRequest, Request},
    http::{header, StatusCode},
    response::{IntoResponse, Response},
};
use prost::Message;
use serde::{Deserialize, Serialize};
use thiserror::Error;

/// Error type for ProtoBuf extractions and responses.
#[derive(Debug, Error)]
pub enum ProtobufError {
    #[error("Invalid Content-Type, expected application/protobuf")]
    InvalidContentType,

    #[error("Failed to read body")]
    ReadBody(#[source] axum::Error),

    #[error("Failed to decode Protobuf")]
    Decode(#[from] prost::DecodeError),

    #[error("Failed to encode Protobuf")]
    Encode(#[from] prost::EncodeError),
}

impl IntoResponse for ProtobufError {
    fn into_response(self) -> Response {
        match self {
            ProtobufError::InvalidContentType => {
                (axum::http::StatusCode::UNSUPPORTED_MEDIA_TYPE, self.to_string()).into_response()
            }
            ProtobufError::Decode(err) => {
                (axum::http::StatusCode::BAD_REQUEST, err.to_string()).into_response()
            }
            _ => (
                axum::http::StatusCode::INTERNAL_SERVER_ERROR,
                self.to_string(),
            )
                .into_response(),
        }
    }
}

/// A wrapper for Protobuf messages that implements Axum's [`FromRequest`] and [`IntoResponse`].
///
/// Use this tuple struct to extract a Protobuf message from a request body or return one in a response.
#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize)]
pub struct Protobuf<T>(pub T);


impl<S, T> FromRequest<S> for Protobuf<T>
where
    T: Message + Default + Send,
    S: Send + Sync,
{
    type Rejection = ProtobufError;

    async fn from_request(req: Request, state: &S) -> Result<Self, Self::Rejection> {
        let has_protobuf = req
            .headers()
            .get_all(header::CONTENT_TYPE)
            .iter()
            .any(|value| {
                value
                    .to_str()
                    .map(|s| s.starts_with("application/protobuf"))
                    .unwrap_or(false)
            });

        if has_protobuf {
            let bytes = Bytes::from_request(req, state)
                .await
                .map_err(|e| ProtobufError::ReadBody(axum::Error::new(e)))?;
            let value = T::decode(bytes)?;
            Ok(Protobuf(value))
        } else {
            Err(ProtobufError::InvalidContentType)
        }
    }
}

impl<T> IntoResponse for Protobuf<T>
where
    T: Message,
{
    fn into_response(self) -> Response {
        let mut buf = Vec::new();
        if let Err(e) = self.0.encode(&mut buf) {
            return (
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("Failed to encode protobuf: {}", e),
            )
                .into_response();
        }

        (
            [(header::CONTENT_TYPE, "application/protobuf")],
            buf,
        )
            .into_response()
    }
}
