//! # Loco ProtoBuf
//!
//! A helper crate to easily integrate Protocol Buffers with [Loco.rs](https://loco.rs),
//! offering Axum-compatible extractors and responses.
//!
//! ## Features
//!
//! - **`Protobuf<T>` Extractor**: Automatically decodes `application/protobuf` request bodies into your Prost-generated structs.
//! - **`Protobuf<T>` Response**: Automatically encodes your structs into Protobuf format and sets the `Content-Type: application/protobuf` header.
//!
//! ## Usage
//!
//! ```rust,no_run
//! use axum::response::Result;
//! use loco_protobuf::Protobuf;
//! // use crate::proto::user::{UserRequest, UserResponse};
//!
//! // Define your Proto structs (usually generated by prost-build)
//! #[derive(prost::Message, Clone)]
//! pub struct UserRequest {
//!     #[prost(string, tag = "1")]
//!     pub id: String,
//! }
//!
//! #[derive(prost::Message, Clone)]
//! pub struct UserResponse {
//!     #[prost(string, tag = "1")]
//!     pub id: String,
//! }
//!
//! async fn create_user(
//!     Protobuf(req): Protobuf<UserRequest>,
//! ) -> Result<Protobuf<UserResponse>> {
//!     Ok(Protobuf(UserResponse {
//!         id: req.id,
//!     }))
//! }
//! ```

// pub mod gen;
use axum::{
    body::Bytes,
    extract::{FromRequest, Request, rejection::BytesRejection},
    http::{header, StatusCode},
    response::{IntoResponse, Response},
};
use prost::Message;

/// Error type for ProtoBuf extractions and responses.
#[derive(Debug)]
pub enum ProtobufError {
    InvalidContentType,
    ReadBody(BytesRejection),
    Decode(prost::DecodeError),
}

impl IntoResponse for ProtobufError {
    fn into_response(self) -> Response {
        match self {
            ProtobufError::InvalidContentType => (
                StatusCode::UNSUPPORTED_MEDIA_TYPE,
                "Invalid Content-Type, expected application/protobuf",
            )
                .into_response(),
            ProtobufError::ReadBody(rejection) => rejection.into_response(),
            ProtobufError::Decode(err) => (
                StatusCode::BAD_REQUEST,
                format!("Failed to decode Protobuf: {}", err),
            )
                .into_response(),
        }
    }
}

impl std::fmt::Display for ProtobufError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ProtobufError::InvalidContentType => write!(f, "Invalid Content-Type, expected application/protobuf"),
            ProtobufError::ReadBody(err) => write!(f, "Failed to read body: {}", err),
            ProtobufError::Decode(err) => write!(f, "Failed to decode Protobuf: {}", err),
        }
    }
}

impl std::error::Error for ProtobufError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            ProtobufError::ReadBody(err) => Some(err),
            ProtobufError::Decode(err) => Some(err),
            _ => None,
        }
    }
}

/// A wrapper for Protobuf messages that implements Axum's [`FromRequest`] and [`IntoResponse`].
///
/// Use this tuple struct to extract a Protobuf message from a request body or return one in a response.
#[derive(Debug, Clone, Default)]
pub struct Protobuf<T>(pub T);

impl<S, T> FromRequest<S> for Protobuf<T>
where
    T: Message + Default + Send,
    S: Send + Sync,
{
    type Rejection = ProtobufError;

    async fn from_request(req: Request, state: &S) -> Result<Self, Self::Rejection> {
        let has_protobuf = req
            .headers()
            .get_all(header::CONTENT_TYPE)
            .iter()
            .any(|value| value.as_bytes().starts_with(b"application/protobuf"));

        if has_protobuf {
            let bytes = Bytes::from_request(req, state)
                .await
                .map_err(ProtobufError::ReadBody)?;
            let value = T::decode(bytes).map_err(ProtobufError::Decode)?;
            Ok(Protobuf(value))
        } else {
            Err(ProtobufError::InvalidContentType)
        }
    }
}

impl<T> IntoResponse for Protobuf<T>
where
    T: Message,
{
    fn into_response(self) -> Response {
        let mut buf = Vec::new();
        match self.0.encode(&mut buf) {
            Ok(_) => (
                [(header::CONTENT_TYPE, "application/protobuf")],
                buf,
            )
                .into_response(),
            Err(err) => (
                StatusCode::INTERNAL_SERVER_ERROR,
                format!("Failed to encode protobuf: {}", err),
            )
                .into_response(),
        }
    }
}
